version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gold_db
    ports:
      - "5432:5432"
    networks:
      - airflow_net

  airflow:
    image: apache/airflow:2.2.2
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/gold_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts  # Chứa mã Python của bạn
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - airflow_net

networks:
  airflow_net:
    driver: bridge